version: '3.1'
services:
  mongodb:
    image: mongo:3.4.2
    container_name: portalx_mongodb
    hostname: portalx_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: portalx
    ports:
      - "27017:27017"
    volumes:
          - ./data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongodb-seed:
    image: mongo:3.4.2
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - ./data:/data
    command:
      'bash -c "mongoimport --host portalx_mongodb --username portalx --password portalx --db portalx --type json --file /data/locations.json --jsonArray"'
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    container_name: portalx_client
    hostname: portalx_client
    depends_on:
      - mongodb
    ports:
      - 80:80
